[Project] Extend release scripts to support release branches/tags with project suffix

diff --git a/autoRelease b/autoRelease
--- a/autoRelease
+++ b/autoRelease
@@ -44,9 +44,15 @@ fi
 echo -e "INFO: Current pom version is ${currentPomVersion}"
 
 # find which major/minor version we are building
-releaseVersion=$(echo -n "$releaseBranch" | cut -d '/' -f 2)
+releaseVersion=$(echo -n "$releaseBranch" | cut -d '/' -f 2 | awk -F'-' '{print $1}')
+releaseSuffix=$(echo -n "$releaseBranch" | cut -d '/' -f 2 | awk -F'-' '{print $2}')
+tagSuffix=""
 echo -e "INFO: releaseVersion: ${releaseVersion}"
-if [[ "${releaseVersion}" == "${releaseBranch}" ]] ; then
+if [ -n "$releaseSuffix" ]; then
+  echo -e "INFO: releaseSuffix: ${releaseSuffix}"
+  tagSuffix="-${releaseSuffix}"
+fi
+if [[ "${releaseVersion}${tagSuffix}" == "${releaseBranch}" ]] ; then
   lastTag=$(git for-each-ref --format="%(refname)" --sort=-taggerdate --count=1 refs/tags | cut -d '/' -f 3)
   if [[ "${lastTag}" == "" ]] ; then
     echo -e "WARN: No tag yet, using pom version ${currentPomVersion} without -SNAPSHOT"
@@ -83,8 +89,8 @@ else
   done
 
   if [[ "${lastTag}" == "" ]] ; then
-    echo -e "WARN: There is no last tag for releaseVersion: ${releaseVersion}, thus using initial version ${releaseVersion}"
-    lastTag=${releaseVersion}
+    echo -e "WARN: There is no last tag for releaseVersion: ${${expectedMajorVersion}}.${expectedMinorVersion}.x, thus using initial version ${releaseVersion}"
+    lastTag=${releaseVersion}${tagSuffix}
     updateType="NONE"
   else
     echo -e "INFO: Previous tag: ${lastTag}"
@@ -129,6 +135,27 @@ fi
 
 # build new version
 newVersion="${majorVersion}.${minorVersion}.${updateVersion}"
+pomReleaseVersion="${currentPomVersion/-SNAPSHOT/}"
+if [[ "newVersion" != "pomReleaseVersion" ]] ;then
+  echo "WARN: POM version and requested release version differ."
+  PS3='Please select the release version to apply: '
+  versions=("${newVersion} (requested)" "${pomReleaseVersion} (POM)" "Quit")
+  select v in "${versions[@]}"; do
+    case $v in
+      "${newVersion} (requested)")
+        break
+        ;;
+      "${pomReleaseVersion} (POM)")
+        newVersion="${pomReleaseVersion}"
+        break
+        ;;
+      "Quit")
+        exit 0
+        ;;
+      *) echo "Invalid option $REPLY";;
+    esac
+  done
+fi
 
 
 # cleanup trap
@@ -142,9 +169,9 @@ trap cleanup EXIT
 
 
 # Confirm
-echo -e "INFO: Do you want to create release/tag ${newVersion} from release branch ${releaseBranch}? [Y/n]"
+echo -e "INFO: Do you want to create release/tag ${newVersion}${tagSuffix} from release branch ${releaseBranch}? [Y/n]"
 read a
-if [[ "${a}" != "" ]] && [[ "${a}" != "y" ]] ; then
+if [[ "${a}" != "" ]] && [[ "${a,,}" != "y" ]] ; then
   exit 0
 fi
 
@@ -230,7 +257,7 @@ if ! git commit -m "[Project] Set new version ${newVersion}" ; then
   echo -e "ERROR: Failed to git commit"
   exit 1
 fi
-if ! git tag --sign --message "[Project] New Version ${newVersion}" "${newVersion}" ; then
+if ! git tag --sign --message "[Project] New Version ${newVersion}" "${newVersion}${tagSuffix}" ; then
   echo -e "ERROR: Failed to git tag"
   exit 1
 fi
@@ -238,8 +265,8 @@ fi
 
 # local install
 echo -e "\nINFO: Installing new version..."
-if ! git checkout "${newVersion}" ; then
-  echo -e "ERROR: Failed to checkout tag ${newVersion}"
+if ! git checkout "${newVersion}${tagSuffix}" ; then
+  echo -e "ERROR: Failed to checkout tag ${newVersion}${tagSuffix}"
   exit 1
 fi
 if ! mvn source:jar install -DskipTests ${MVN_PROFILES} > /dev/null ; then
@@ -281,9 +308,9 @@ if ! git push origin "${releaseBranch}" --follow-tags ; then
   echo -e "ERROR: Failed to push changes"
   exit 1
 fi
-echo -e "\nINFO: Pushed Release/Tag ${newVersion}"
+echo -e "\nINFO: Pushed Release/Tag ${newVersion}${tagSuffix}"
 
 
 rm -f "${logFile}"
-echo -e "\nINFO: Release/Tag ${newVersion} created."
+echo -e "\nINFO: Release/Tag ${newVersion}${tagSuffix} created."
 exit 0
